import { defineTextStyles } from "@chakra-ui/react";

export const textStyles = defineTextStyles({
  navbar: {
    description: "nav bar styling",
    value: {
      fontFamily: "sans-serif",
      fontWeight: "500",
      fontSize: "2xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  button: {
	description: "button",
    value: {
      fontFamily: "sans-serif",
      fontWeight: "500",
      fontSize: "2xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  homePageWelcome: {
    description: "home page welcome",
    value: {
      fontFamily: "Changa One",
      fontWeight: "400",
      fontSize: "4xl",
      fontStyle: "italic",
      lineHeight: "taller",
      letterSpacing: "4",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  homePageWelcomeContent: {
    description: "home page welcome",
    value: {
      fontFamily: "sans-serif",
      fontWeight: "400",
      fontSize: "xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  homePageContent: {
    description: "home page content styling",
    value: {
      fontFamily: "sans-serif",
      fontWeight: "500",
      fontSize: "2xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  homePageProjectTitle: {
    description: "home page project overview title",
    value: {
      fontFamily: "Changa One",
      fontWeight: "400",
      fontSize: "2xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  homePageProjectSubtitle: {
    description: "home page project overview title",
    value: {
      fontFamily: "Changa One",
      fontWeight: "400",
      fontSize: "md",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  projectPageTitle: {
    description: "project page project title",
    value: {
      fontFamily: "sans-serif",
      fontWeight: "500",
      fontSize: "3xl",
      lineHeight: "tall",
      letterSpacing: "2",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  aboutPageTitle: {
    description: "about page title",
    value: {
      fontFamily: "Changa One",
      fontWeight: "400",
      fontSize: "4xl",
      fontStyle: "italic",
      lineHeight: "taller",
      letterSpacing: "4",
      textDecoration: "None",
      textTransform: "None",
    },
  },
  aboutPageContent: {
    description: "about page content",
    value: {
      fontFamily: "Changa One",
      fontWeight: "200",
      fontSize: "lg",
      fontStyle: "normal",
      lineHeight: "taller",
      letterSpacing: "4",
      textDecoration: "None",
      textTransform: "None",
    },
  },
});
